{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm1.serviceAccountName" . }}
  labels:
{{ include "helm1.labels" . | indent 4 }}
{{- end -}}
